// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Soporte",
            "email": "osramirezdev@mail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/persona/{cedula}": {
            "get": {
                "description": "Se obtiene dato de persona por cedula, si no existe en base de datos se busca por scraping.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Personas"
                ],
                "summary": "busqueda datos de persona por cedula",
                "parameters": [
                    {
                        "maxLength": 10,
                        "minLength": 6,
                        "type": "string",
                        "description": "Debe introducir un numero de cedula",
                        "name": "cedula",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Debe introducir un tipo de busqueda, puede ser 'ruc', 'ips', 'funcionario'",
                        "name": "tipo",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseDto-int"
                        }
                    },
                    "404": {
                        "description": "No se encontraron datos",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseDto404"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseDto500"
                        }
                    }
                }
            }
        },
        "/v1/scraper/obtener/funcionarios/": {
            "post": {
                "description": "Validad si una cedula pertenece a un funcionario publico.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scraper"
                ],
                "summary": "Permite consultar si datos de funcionarios existen por cedula, mes y anho",
                "parameters": [
                    {
                        "description": "Dto para consultar datos",
                        "name": "funcionario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.FuncionarioDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseDto-dtos_Funcionario"
                        }
                    },
                    "404": {
                        "description": "No se encontro asegurado",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseDto404"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseDto500"
                        }
                    }
                }
            }
        },
        "/v1/scraper/obtener/ips/": {
            "post": {
                "description": "Hacer scraping de ips.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scraper"
                ],
                "summary": "Permite consultar datos de asegiurados por cedula",
                "parameters": [
                    {
                        "description": "Dto para consultar datos",
                        "name": "ips",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.IpsDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseDto-dtos_Asegurado"
                        }
                    },
                    "404": {
                        "description": "No se encontro asegurado",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseDto404"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseDto500"
                        }
                    }
                }
            }
        },
        "/v1/scraper/obtener/ruc/": {
            "post": {
                "description": "Permite consultar si ruc existen por cedula o nombre.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scraper"
                ],
                "summary": "scraping de documentos o nombres",
                "parameters": [
                    {
                        "description": "Nombres es campo opcional",
                        "name": "ruc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.RucDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseDto-int"
                        }
                    },
                    "404": {
                        "description": "No se encontro ruc",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseDto404"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ResponseDto500"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.Asegurado": {
            "type": "object",
            "properties": {
                "apellidos": {
                    "type": "string"
                },
                "beneficiarios_activos": {
                    "type": "string"
                },
                "documento": {
                    "type": "string"
                },
                "empleadores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Empleador"
                    }
                },
                "enrolado": {
                    "type": "string"
                },
                "fecha_nacimiento": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nombres": {
                    "type": "string"
                },
                "sexo": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                },
                "vencimiento": {
                    "type": "string"
                }
            }
        },
        "dtos.Asignacion": {
            "type": "object",
            "properties": {
                "actualizacion": {
                    "type": "string"
                },
                "cargo": {
                    "type": "string"
                },
                "categoria": {
                    "type": "string"
                },
                "correo": {
                    "type": "string"
                },
                "devengado": {
                    "type": "integer"
                },
                "estado": {
                    "type": "string"
                },
                "fecha_administrativo": {
                    "type": "string"
                },
                "financiamiento": {
                    "type": "string"
                },
                "funcion": {
                    "type": "string"
                },
                "gasto": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "linea": {
                    "type": "string"
                },
                "lugar": {
                    "type": "string"
                },
                "motivo_movimiento": {
                    "type": "string"
                },
                "movimiento": {
                    "type": "string"
                },
                "oficina": {
                    "type": "string"
                },
                "presupuestado": {
                    "type": "integer"
                },
                "profesion": {
                    "type": "string"
                }
            }
        },
        "dtos.Empleador": {
            "type": "object",
            "properties": {
                "abonado": {
                    "type": "string"
                },
                "aportes": {
                    "type": "integer"
                },
                "empleador": {
                    "type": "string"
                },
                "estado": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "patronal": {
                    "type": "string"
                },
                "vencimiento": {
                    "type": "string"
                }
            }
        },
        "dtos.Funcionario": {
            "type": "object",
            "properties": {
                "anho": {
                    "type": "integer"
                },
                "anho_inicio": {
                    "type": "integer"
                },
                "apellidos": {
                    "type": "string"
                },
                "asignaciones": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Asignacion"
                    }
                },
                "devengado": {
                    "type": "integer"
                },
                "discapacidad": {
                    "type": "string"
                },
                "documento": {
                    "type": "string"
                },
                "entidad": {
                    "type": "string"
                },
                "estado": {
                    "type": "string"
                },
                "fecha_nacimiento": {
                    "type": "string"
                },
                "horario": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mes": {
                    "type": "string"
                },
                "nivel": {
                    "type": "string"
                },
                "nombres": {
                    "type": "string"
                },
                "oee": {
                    "type": "string"
                },
                "presupuestado": {
                    "type": "integer"
                },
                "sexo": {
                    "type": "string"
                },
                "tipo_discapacidad": {
                    "type": "string"
                }
            }
        },
        "dtos.FuncionarioDto": {
            "type": "object",
            "required": [
                "search"
            ],
            "properties": {
                "search": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Search"
                    }
                }
            }
        },
        "dtos.IpsDto": {
            "type": "object",
            "required": [
                "documentos"
            ],
            "properties": {
                "documentos": {
                    "type": "array",
                    "maxItems": 500,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dtos.ResponseDto-dtos_Asegurado": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Asegurado"
                    }
                },
                "error": {
                    "type": "boolean",
                    "default": false
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "dtos.ResponseDto-dtos_Funcionario": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Funcionario"
                    }
                },
                "error": {
                    "type": "boolean",
                    "default": false
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "dtos.ResponseDto-int": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "error": {
                    "type": "boolean",
                    "default": false
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "dtos.ResponseDto404": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "count": {
                    "type": "integer",
                    "default": 0
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "error": {
                    "type": "boolean",
                    "default": true
                },
                "msg": {
                    "type": "string",
                    "default": "Not found"
                }
            }
        },
        "dtos.ResponseDto500": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "count": {
                    "type": "integer",
                    "default": 0
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "error": {
                    "type": "boolean",
                    "default": true
                },
                "msg": {
                    "type": "string",
                    "default": "Internal server error"
                }
            }
        },
        "dtos.RucDto": {
            "type": "object",
            "required": [
                "documentos"
            ],
            "properties": {
                "documentos": {
                    "type": "array",
                    "maxItems": 500,
                    "items": {
                        "type": "string"
                    }
                },
                "nombres": {
                    "description": "optional fields",
                    "type": "array",
                    "maxItems": 500,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dtos.Search": {
            "type": "object",
            "required": [
                "documento"
            ],
            "properties": {
                "documento": {
                    "type": "string",
                    "example": "900999"
                },
                "tipo": {
                    "type": "string",
                    "example": "ruc"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "API Scraper Persona",
	Description:      "Api para consultar datos de cedula via web.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
